stack:
  name: "Back-end Stack"
  repository:
    url: https://github.com/Kae134/Aittention
    ref: spacelift-fix

workflow:
  init:
    - name: "Install ✔"
      command: |
        echo "✔ Install"
        cd backend
        pip install -r requirements.txt

    - name: "Tests 🚧"
      command: |
        echo "🚧 Lancements tests unitaires"
        cd backend
        pytest --maxfail=1 --disable-warnings -q
        if [ $? -eq 0 ]; then
          echo "✔ Tests effectués avec succès ✔"
        else
          echo "❌ Échec des tests"
          exit 1
        fi
